drop table IF EXISTS mpa_ratings CASCADE;
drop table IF EXISTS genres CASCADE;
drop table IF EXISTS films CASCADE;
drop table IF EXISTS users CASCADE;
drop table IF EXISTS likes CASCADE;
drop table IF EXISTS friends CASCADE;
drop table IF EXISTS film_genres CASCADE;

CREATE TABLE IF NOT EXISTS mpa_ratings
(
    id   int         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    CONSTRAINT pk_mpa_ratings PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS genres
(
    id   int          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS films
(
    id           int GENERATED BY DEFAULT AS IDENTITY,
    name         varchar,
    description  varchar,
    release_date date,
    duration     int,
    rate         int,
    mpa_rating   int REFERENCES mpa_ratings (id) ON DELETE CASCADE,
    CONSTRAINT pk_films PRIMARY KEY (id),
    CONSTRAINT name_release_date UNIQUE (name, release_date)
);

CREATE TABLE IF NOT EXISTS users
(
    id       int GENERATED BY DEFAULT AS IDENTITY,
    email    varchar,
    login    varchar,
    name     varchar,
    birthday date,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS likes
(
    id      int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    film_id int NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    user_id int NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS friends
(
    id           int     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id      int     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    friend_id    int     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    is_confirmed boolean NOT NULL,
    CONSTRAINT pk_friends PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS film_genres
(
    id       int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    film_id  int NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    genre_id int NOT NULL REFERENCES genres (id) ON DELETE CASCADE,
    CONSTRAINT pk_film_genres PRIMARY KEY (id)
);